### PR TITLE
added logout page

### PR DESCRIPTION
**Pull request by yogesh-**
Added a logout page which opens up when users click on logout button from the navigation.

image

### CODE REVIEW

**Review by JowelTisso — APPROVED** [review]
Looks Good

**Review by shivampandey0 — COMMENTED** [review]
Well, Structured code with Use of CSS variables.
Good to merge

**Review by pariyar07 — APPROVED** [review]
Clean code looks good to merge.

**Review by sanjitsarkar — COMMENTED** [review]
Fix contrast issues like the site title in header

**Comment by pariyar07** [comment]
Just some contrast issue. Please fix that. Others good to merge.

**Pull request merged**
